title: Yuxing Chen # your name (or website title) here
logo: "/images/Profile21.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a data analyst 
  <br><br>
  Result-oriented and analytics-driven former business leader with 10+ years of in-depth research, analytics, and customer success experience. Solid analytical, interpersonal, problem-solving and critical-thinking skills for driving business growth. Currently looking to leverage my hands-on experience in developing insights from both quantitative and qualitative data. 
  <br><br>
  <a href="">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
