title: Yuxing Chen
logo: "/images/Profile21.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Result-oriented and analytics-driven former business leader with 10+ years of in-depth research, analytics, and customer success experience. Currently looking to leverage my hands-on experience in developing insights from both quantitative and qualitative data.
  <br><br>
  <a href="https://public.tableau.com/app/profile/angelo.chen">View My Tableau Work Samples</a>
  <a href="https://www.notion.so/angelochen/Portfolio-ea70562142f84f04a304969058ff5c7f">View My Notion Portfolio</a>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
theme: jekyll-theme-minimal
